name: Deploy to S3

on:
  push:
    branches: [ master ]
  workflow_dispatch:

# env:
#   AWS_REGION: us-east-1
#   S3_BUCKET: your-s3-bucket-name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Deploy to S3
      run: |
        aws s3 sync . s3://${{ secrets.S3_BUCKET }} \
          --exclude ".git/*" \
          --exclude ".github/*"